### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'`

### ISSUE THREAD

**Issue by zelenooki87** [hongyuanyu/SPAN#1]
Thanks for great work. However I cannot run code.
`C:\Users\Mika\SPAN-main>python setup.py develop --no_cuda_ext
Traceback (most recent call last):
  File "C:\Users\Mika\SPAN-main\setup.py", line 146, in <module>
    write_version_py()
  File "C:\Users\Mika\SPAN-main\setup.py", line 67, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'`
please fix it

**Comment by hongyuanyu** [comment]
Thanks for your attention, this issue has been fixed.
